// This file is automatically generated. Do not edit it manually. cf https://www.swarmion.dev/docs/how-to-guides/use-integration-tests
import { getTestEnvVars } from '@swarmion/integration-tests';

export type TestEnvVarsType = {
  TABLE_NAME: string;
  EVENT_BUS_NAME: string;
  API_URL: string;
};

export const TEST_ENV_VARS = getTestEnvVars<TestEnvVarsType>();
