name: 'Lint & Test'
description: 'Run linters and tests on app or library'
inputs:
  path:
    required: true
    description: 'Path to the directory to lint and test'
runs:
  using: 'composite'
  steps:
    - name: Install & cache node dependencies
      uses: ./.github/actions/install-node-deps
    - name: Run lint
      run: |
        cd ${{ inputs.path }}
        pnpm test-linter --max-warnings 0
      shell: bash
    - name: Run stylelint
      run: |
        cd ${{ inputs.path }}
        if [[ $(cat package.json | jq '.scripts["test-stylelint"]') != null ]]; then
          pnpm test-stylelint
        else
          echo "No stylelint test script found in package.json"
        fi
      shell: bash
    - name: Run unit tests
      run: |
        cd ${{ inputs.path }}
        if [[ $(cat package.json | jq '.scripts["test-unit"]') != null ]]; then
          pnpm test-unit
        else
          echo "No unit test script found in package.json"
        fi
      shell: bash
    - name: Run type test
      run: |
        cd ${{ inputs.path }}
        if [[ $(cat package.json | jq '.scripts["test-type"]') != null ]]; then
          pnpm test-type
        else
          echo "No type test script found in package.json"
        fi
      shell: bash
    - name: Run circular dependencies test
      run: |
        cd ${{ inputs.path }}
        if [[ $(cat package.json | jq '.scripts["test-circular"]') != null ]]; then
          pnpm test-circular
        else
          echo "No circular dependencies test script found in package.json"
        fi
      shell: bash
