name: 'Run package'
description: 'Package all libraries in the monorepo'
runs:
  using: 'composite'
  steps:
    - name: Cache package builds
      id: package-cache
      uses: actions/cache@v2
      with:
        path: |
          nx-cache
        key: ${{ runner.os }}-packages-${{ env.NODE_VERSION }}-${{ hashFiles('contracts/**/*.ts', 'packages/**/*.ts') }}
        restore-keys: |
          ${{ runner.os }}-packages-${{ env.NODE_VERSION }}-
          ${{ runner.os }}-packages-
          ${{ runner.os }}-
    - name: Run package
      run: pnpm package
      shell: bash
