name: 🐇 CodSpeed benchmarks

on:
  push:
    branches:
      - 'main'
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

# cancel previous runs on the same PR
concurrency:
  group: ${{ github.ref }}/codspeed
  cancel-in-progress: true

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
      - name: Install & cache node dependencies
        uses: ./.github/actions/install-node-deps
      - name: Package the repo
        run: pnpm package
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: instrumentation
          run: pnpm -r bench
