name: 🔖 Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install & cache node dependencies
        uses: ./.github/actions/install-node-deps

      - name: Get latest release matching release tag type
        id: get-latest-release
        uses: rez0n/actions-github-release@main
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          # 'prerelease' if tag inclues 'alpha', otherwise 'stable'
          type: ${{ contains(github.ref, 'alpha') && 'prerelease' || 'stable' }}

      - run: pnpm changelogithub --draft --from ${{ steps.get-latest-release.outputs.release }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
